// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/tobyrushton/padel-stats/libs/games"
)

type FakeRepository struct {
	CreateGameStub        func(context.Context, *games.GameRecord) error
	createGameMutex       sync.RWMutex
	createGameArgsForCall []struct {
		arg1 context.Context
		arg2 *games.GameRecord
	}
	createGameReturns struct {
		result1 error
	}
	createGameReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteGameByIDStub        func(context.Context, int64) error
	deleteGameByIDMutex       sync.RWMutex
	deleteGameByIDArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	deleteGameByIDReturns struct {
		result1 error
	}
	deleteGameByIDReturnsOnCall map[int]struct {
		result1 error
	}
	FindGameByIDStub        func(context.Context, int64) (*games.GameRecord, error)
	findGameByIDMutex       sync.RWMutex
	findGameByIDArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	findGameByIDReturns struct {
		result1 *games.GameRecord
		result2 error
	}
	findGameByIDReturnsOnCall map[int]struct {
		result1 *games.GameRecord
		result2 error
	}
	FindGamesByPlayerIDStub        func(context.Context, int64) ([]*games.GameRecord, error)
	findGamesByPlayerIDMutex       sync.RWMutex
	findGamesByPlayerIDArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	findGamesByPlayerIDReturns struct {
		result1 []*games.GameRecord
		result2 error
	}
	findGamesByPlayerIDReturnsOnCall map[int]struct {
		result1 []*games.GameRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRepository) CreateGame(arg1 context.Context, arg2 *games.GameRecord) error {
	fake.createGameMutex.Lock()
	ret, specificReturn := fake.createGameReturnsOnCall[len(fake.createGameArgsForCall)]
	fake.createGameArgsForCall = append(fake.createGameArgsForCall, struct {
		arg1 context.Context
		arg2 *games.GameRecord
	}{arg1, arg2})
	stub := fake.CreateGameStub
	fakeReturns := fake.createGameReturns
	fake.recordInvocation("CreateGame", []interface{}{arg1, arg2})
	fake.createGameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepository) CreateGameCallCount() int {
	fake.createGameMutex.RLock()
	defer fake.createGameMutex.RUnlock()
	return len(fake.createGameArgsForCall)
}

func (fake *FakeRepository) CreateGameCalls(stub func(context.Context, *games.GameRecord) error) {
	fake.createGameMutex.Lock()
	defer fake.createGameMutex.Unlock()
	fake.CreateGameStub = stub
}

func (fake *FakeRepository) CreateGameArgsForCall(i int) (context.Context, *games.GameRecord) {
	fake.createGameMutex.RLock()
	defer fake.createGameMutex.RUnlock()
	argsForCall := fake.createGameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepository) CreateGameReturns(result1 error) {
	fake.createGameMutex.Lock()
	defer fake.createGameMutex.Unlock()
	fake.CreateGameStub = nil
	fake.createGameReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) CreateGameReturnsOnCall(i int, result1 error) {
	fake.createGameMutex.Lock()
	defer fake.createGameMutex.Unlock()
	fake.CreateGameStub = nil
	if fake.createGameReturnsOnCall == nil {
		fake.createGameReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createGameReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) DeleteGameByID(arg1 context.Context, arg2 int64) error {
	fake.deleteGameByIDMutex.Lock()
	ret, specificReturn := fake.deleteGameByIDReturnsOnCall[len(fake.deleteGameByIDArgsForCall)]
	fake.deleteGameByIDArgsForCall = append(fake.deleteGameByIDArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.DeleteGameByIDStub
	fakeReturns := fake.deleteGameByIDReturns
	fake.recordInvocation("DeleteGameByID", []interface{}{arg1, arg2})
	fake.deleteGameByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepository) DeleteGameByIDCallCount() int {
	fake.deleteGameByIDMutex.RLock()
	defer fake.deleteGameByIDMutex.RUnlock()
	return len(fake.deleteGameByIDArgsForCall)
}

func (fake *FakeRepository) DeleteGameByIDCalls(stub func(context.Context, int64) error) {
	fake.deleteGameByIDMutex.Lock()
	defer fake.deleteGameByIDMutex.Unlock()
	fake.DeleteGameByIDStub = stub
}

func (fake *FakeRepository) DeleteGameByIDArgsForCall(i int) (context.Context, int64) {
	fake.deleteGameByIDMutex.RLock()
	defer fake.deleteGameByIDMutex.RUnlock()
	argsForCall := fake.deleteGameByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepository) DeleteGameByIDReturns(result1 error) {
	fake.deleteGameByIDMutex.Lock()
	defer fake.deleteGameByIDMutex.Unlock()
	fake.DeleteGameByIDStub = nil
	fake.deleteGameByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) DeleteGameByIDReturnsOnCall(i int, result1 error) {
	fake.deleteGameByIDMutex.Lock()
	defer fake.deleteGameByIDMutex.Unlock()
	fake.DeleteGameByIDStub = nil
	if fake.deleteGameByIDReturnsOnCall == nil {
		fake.deleteGameByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteGameByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepository) FindGameByID(arg1 context.Context, arg2 int64) (*games.GameRecord, error) {
	fake.findGameByIDMutex.Lock()
	ret, specificReturn := fake.findGameByIDReturnsOnCall[len(fake.findGameByIDArgsForCall)]
	fake.findGameByIDArgsForCall = append(fake.findGameByIDArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.FindGameByIDStub
	fakeReturns := fake.findGameByIDReturns
	fake.recordInvocation("FindGameByID", []interface{}{arg1, arg2})
	fake.findGameByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepository) FindGameByIDCallCount() int {
	fake.findGameByIDMutex.RLock()
	defer fake.findGameByIDMutex.RUnlock()
	return len(fake.findGameByIDArgsForCall)
}

func (fake *FakeRepository) FindGameByIDCalls(stub func(context.Context, int64) (*games.GameRecord, error)) {
	fake.findGameByIDMutex.Lock()
	defer fake.findGameByIDMutex.Unlock()
	fake.FindGameByIDStub = stub
}

func (fake *FakeRepository) FindGameByIDArgsForCall(i int) (context.Context, int64) {
	fake.findGameByIDMutex.RLock()
	defer fake.findGameByIDMutex.RUnlock()
	argsForCall := fake.findGameByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepository) FindGameByIDReturns(result1 *games.GameRecord, result2 error) {
	fake.findGameByIDMutex.Lock()
	defer fake.findGameByIDMutex.Unlock()
	fake.FindGameByIDStub = nil
	fake.findGameByIDReturns = struct {
		result1 *games.GameRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeRepository) FindGameByIDReturnsOnCall(i int, result1 *games.GameRecord, result2 error) {
	fake.findGameByIDMutex.Lock()
	defer fake.findGameByIDMutex.Unlock()
	fake.FindGameByIDStub = nil
	if fake.findGameByIDReturnsOnCall == nil {
		fake.findGameByIDReturnsOnCall = make(map[int]struct {
			result1 *games.GameRecord
			result2 error
		})
	}
	fake.findGameByIDReturnsOnCall[i] = struct {
		result1 *games.GameRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeRepository) FindGamesByPlayerID(arg1 context.Context, arg2 int64) ([]*games.GameRecord, error) {
	fake.findGamesByPlayerIDMutex.Lock()
	ret, specificReturn := fake.findGamesByPlayerIDReturnsOnCall[len(fake.findGamesByPlayerIDArgsForCall)]
	fake.findGamesByPlayerIDArgsForCall = append(fake.findGamesByPlayerIDArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.FindGamesByPlayerIDStub
	fakeReturns := fake.findGamesByPlayerIDReturns
	fake.recordInvocation("FindGamesByPlayerID", []interface{}{arg1, arg2})
	fake.findGamesByPlayerIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepository) FindGamesByPlayerIDCallCount() int {
	fake.findGamesByPlayerIDMutex.RLock()
	defer fake.findGamesByPlayerIDMutex.RUnlock()
	return len(fake.findGamesByPlayerIDArgsForCall)
}

func (fake *FakeRepository) FindGamesByPlayerIDCalls(stub func(context.Context, int64) ([]*games.GameRecord, error)) {
	fake.findGamesByPlayerIDMutex.Lock()
	defer fake.findGamesByPlayerIDMutex.Unlock()
	fake.FindGamesByPlayerIDStub = stub
}

func (fake *FakeRepository) FindGamesByPlayerIDArgsForCall(i int) (context.Context, int64) {
	fake.findGamesByPlayerIDMutex.RLock()
	defer fake.findGamesByPlayerIDMutex.RUnlock()
	argsForCall := fake.findGamesByPlayerIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepository) FindGamesByPlayerIDReturns(result1 []*games.GameRecord, result2 error) {
	fake.findGamesByPlayerIDMutex.Lock()
	defer fake.findGamesByPlayerIDMutex.Unlock()
	fake.FindGamesByPlayerIDStub = nil
	fake.findGamesByPlayerIDReturns = struct {
		result1 []*games.GameRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeRepository) FindGamesByPlayerIDReturnsOnCall(i int, result1 []*games.GameRecord, result2 error) {
	fake.findGamesByPlayerIDMutex.Lock()
	defer fake.findGamesByPlayerIDMutex.Unlock()
	fake.FindGamesByPlayerIDStub = nil
	if fake.findGamesByPlayerIDReturnsOnCall == nil {
		fake.findGamesByPlayerIDReturnsOnCall = make(map[int]struct {
			result1 []*games.GameRecord
			result2 error
		})
	}
	fake.findGamesByPlayerIDReturnsOnCall[i] = struct {
		result1 []*games.GameRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ games.Repository = new(FakeRepository)
