// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/tobyrushton/padel-stats/libs/leaderboard"
)

type FakeLeaderboardRepository struct {
	FindAllTimeLeaderboardStub        func(context.Context) ([]*leaderboard.EntryRecord, error)
	findAllTimeLeaderboardMutex       sync.RWMutex
	findAllTimeLeaderboardArgsForCall []struct {
		arg1 context.Context
	}
	findAllTimeLeaderboardReturns struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}
	findAllTimeLeaderboardReturnsOnCall map[int]struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}
	FindSeasonLeaderboardStub        func(context.Context, int64) ([]*leaderboard.EntryRecord, error)
	findSeasonLeaderboardMutex       sync.RWMutex
	findSeasonLeaderboardArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	findSeasonLeaderboardReturns struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}
	findSeasonLeaderboardReturnsOnCall map[int]struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLeaderboardRepository) FindAllTimeLeaderboard(arg1 context.Context) ([]*leaderboard.EntryRecord, error) {
	fake.findAllTimeLeaderboardMutex.Lock()
	ret, specificReturn := fake.findAllTimeLeaderboardReturnsOnCall[len(fake.findAllTimeLeaderboardArgsForCall)]
	fake.findAllTimeLeaderboardArgsForCall = append(fake.findAllTimeLeaderboardArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.FindAllTimeLeaderboardStub
	fakeReturns := fake.findAllTimeLeaderboardReturns
	fake.recordInvocation("FindAllTimeLeaderboard", []interface{}{arg1})
	fake.findAllTimeLeaderboardMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLeaderboardRepository) FindAllTimeLeaderboardCallCount() int {
	fake.findAllTimeLeaderboardMutex.RLock()
	defer fake.findAllTimeLeaderboardMutex.RUnlock()
	return len(fake.findAllTimeLeaderboardArgsForCall)
}

func (fake *FakeLeaderboardRepository) FindAllTimeLeaderboardCalls(stub func(context.Context) ([]*leaderboard.EntryRecord, error)) {
	fake.findAllTimeLeaderboardMutex.Lock()
	defer fake.findAllTimeLeaderboardMutex.Unlock()
	fake.FindAllTimeLeaderboardStub = stub
}

func (fake *FakeLeaderboardRepository) FindAllTimeLeaderboardArgsForCall(i int) context.Context {
	fake.findAllTimeLeaderboardMutex.RLock()
	defer fake.findAllTimeLeaderboardMutex.RUnlock()
	argsForCall := fake.findAllTimeLeaderboardArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeLeaderboardRepository) FindAllTimeLeaderboardReturns(result1 []*leaderboard.EntryRecord, result2 error) {
	fake.findAllTimeLeaderboardMutex.Lock()
	defer fake.findAllTimeLeaderboardMutex.Unlock()
	fake.FindAllTimeLeaderboardStub = nil
	fake.findAllTimeLeaderboardReturns = struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeLeaderboardRepository) FindAllTimeLeaderboardReturnsOnCall(i int, result1 []*leaderboard.EntryRecord, result2 error) {
	fake.findAllTimeLeaderboardMutex.Lock()
	defer fake.findAllTimeLeaderboardMutex.Unlock()
	fake.FindAllTimeLeaderboardStub = nil
	if fake.findAllTimeLeaderboardReturnsOnCall == nil {
		fake.findAllTimeLeaderboardReturnsOnCall = make(map[int]struct {
			result1 []*leaderboard.EntryRecord
			result2 error
		})
	}
	fake.findAllTimeLeaderboardReturnsOnCall[i] = struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeLeaderboardRepository) FindSeasonLeaderboard(arg1 context.Context, arg2 int64) ([]*leaderboard.EntryRecord, error) {
	fake.findSeasonLeaderboardMutex.Lock()
	ret, specificReturn := fake.findSeasonLeaderboardReturnsOnCall[len(fake.findSeasonLeaderboardArgsForCall)]
	fake.findSeasonLeaderboardArgsForCall = append(fake.findSeasonLeaderboardArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.FindSeasonLeaderboardStub
	fakeReturns := fake.findSeasonLeaderboardReturns
	fake.recordInvocation("FindSeasonLeaderboard", []interface{}{arg1, arg2})
	fake.findSeasonLeaderboardMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLeaderboardRepository) FindSeasonLeaderboardCallCount() int {
	fake.findSeasonLeaderboardMutex.RLock()
	defer fake.findSeasonLeaderboardMutex.RUnlock()
	return len(fake.findSeasonLeaderboardArgsForCall)
}

func (fake *FakeLeaderboardRepository) FindSeasonLeaderboardCalls(stub func(context.Context, int64) ([]*leaderboard.EntryRecord, error)) {
	fake.findSeasonLeaderboardMutex.Lock()
	defer fake.findSeasonLeaderboardMutex.Unlock()
	fake.FindSeasonLeaderboardStub = stub
}

func (fake *FakeLeaderboardRepository) FindSeasonLeaderboardArgsForCall(i int) (context.Context, int64) {
	fake.findSeasonLeaderboardMutex.RLock()
	defer fake.findSeasonLeaderboardMutex.RUnlock()
	argsForCall := fake.findSeasonLeaderboardArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeLeaderboardRepository) FindSeasonLeaderboardReturns(result1 []*leaderboard.EntryRecord, result2 error) {
	fake.findSeasonLeaderboardMutex.Lock()
	defer fake.findSeasonLeaderboardMutex.Unlock()
	fake.FindSeasonLeaderboardStub = nil
	fake.findSeasonLeaderboardReturns = struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeLeaderboardRepository) FindSeasonLeaderboardReturnsOnCall(i int, result1 []*leaderboard.EntryRecord, result2 error) {
	fake.findSeasonLeaderboardMutex.Lock()
	defer fake.findSeasonLeaderboardMutex.Unlock()
	fake.FindSeasonLeaderboardStub = nil
	if fake.findSeasonLeaderboardReturnsOnCall == nil {
		fake.findSeasonLeaderboardReturnsOnCall = make(map[int]struct {
			result1 []*leaderboard.EntryRecord
			result2 error
		})
	}
	fake.findSeasonLeaderboardReturnsOnCall[i] = struct {
		result1 []*leaderboard.EntryRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeLeaderboardRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLeaderboardRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ leaderboard.LeaderboardRepository = new(FakeLeaderboardRepository)
