// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/tobyrushton/padel-stats/libs/seasons"
)

type FakeSeasonsRepository struct {
	CreateSeasonStub        func(context.Context, *seasons.CreateSeasonInput) (*seasons.Season, error)
	createSeasonMutex       sync.RWMutex
	createSeasonArgsForCall []struct {
		arg1 context.Context
		arg2 *seasons.CreateSeasonInput
	}
	createSeasonReturns struct {
		result1 *seasons.Season
		result2 error
	}
	createSeasonReturnsOnCall map[int]struct {
		result1 *seasons.Season
		result2 error
	}
	EndSeasonStub        func(context.Context, int64) (*seasons.Season, error)
	endSeasonMutex       sync.RWMutex
	endSeasonArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	endSeasonReturns struct {
		result1 *seasons.Season
		result2 error
	}
	endSeasonReturnsOnCall map[int]struct {
		result1 *seasons.Season
		result2 error
	}
	GetActiveSeasonStub        func(context.Context) (*seasons.Season, error)
	getActiveSeasonMutex       sync.RWMutex
	getActiveSeasonArgsForCall []struct {
		arg1 context.Context
	}
	getActiveSeasonReturns struct {
		result1 *seasons.Season
		result2 error
	}
	getActiveSeasonReturnsOnCall map[int]struct {
		result1 *seasons.Season
		result2 error
	}
	GetSeasonsStub        func(context.Context) ([]*seasons.Season, error)
	getSeasonsMutex       sync.RWMutex
	getSeasonsArgsForCall []struct {
		arg1 context.Context
	}
	getSeasonsReturns struct {
		result1 []*seasons.Season
		result2 error
	}
	getSeasonsReturnsOnCall map[int]struct {
		result1 []*seasons.Season
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSeasonsRepository) CreateSeason(arg1 context.Context, arg2 *seasons.CreateSeasonInput) (*seasons.Season, error) {
	fake.createSeasonMutex.Lock()
	ret, specificReturn := fake.createSeasonReturnsOnCall[len(fake.createSeasonArgsForCall)]
	fake.createSeasonArgsForCall = append(fake.createSeasonArgsForCall, struct {
		arg1 context.Context
		arg2 *seasons.CreateSeasonInput
	}{arg1, arg2})
	stub := fake.CreateSeasonStub
	fakeReturns := fake.createSeasonReturns
	fake.recordInvocation("CreateSeason", []interface{}{arg1, arg2})
	fake.createSeasonMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSeasonsRepository) CreateSeasonCallCount() int {
	fake.createSeasonMutex.RLock()
	defer fake.createSeasonMutex.RUnlock()
	return len(fake.createSeasonArgsForCall)
}

func (fake *FakeSeasonsRepository) CreateSeasonCalls(stub func(context.Context, *seasons.CreateSeasonInput) (*seasons.Season, error)) {
	fake.createSeasonMutex.Lock()
	defer fake.createSeasonMutex.Unlock()
	fake.CreateSeasonStub = stub
}

func (fake *FakeSeasonsRepository) CreateSeasonArgsForCall(i int) (context.Context, *seasons.CreateSeasonInput) {
	fake.createSeasonMutex.RLock()
	defer fake.createSeasonMutex.RUnlock()
	argsForCall := fake.createSeasonArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSeasonsRepository) CreateSeasonReturns(result1 *seasons.Season, result2 error) {
	fake.createSeasonMutex.Lock()
	defer fake.createSeasonMutex.Unlock()
	fake.CreateSeasonStub = nil
	fake.createSeasonReturns = struct {
		result1 *seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) CreateSeasonReturnsOnCall(i int, result1 *seasons.Season, result2 error) {
	fake.createSeasonMutex.Lock()
	defer fake.createSeasonMutex.Unlock()
	fake.CreateSeasonStub = nil
	if fake.createSeasonReturnsOnCall == nil {
		fake.createSeasonReturnsOnCall = make(map[int]struct {
			result1 *seasons.Season
			result2 error
		})
	}
	fake.createSeasonReturnsOnCall[i] = struct {
		result1 *seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) EndSeason(arg1 context.Context, arg2 int64) (*seasons.Season, error) {
	fake.endSeasonMutex.Lock()
	ret, specificReturn := fake.endSeasonReturnsOnCall[len(fake.endSeasonArgsForCall)]
	fake.endSeasonArgsForCall = append(fake.endSeasonArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.EndSeasonStub
	fakeReturns := fake.endSeasonReturns
	fake.recordInvocation("EndSeason", []interface{}{arg1, arg2})
	fake.endSeasonMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSeasonsRepository) EndSeasonCallCount() int {
	fake.endSeasonMutex.RLock()
	defer fake.endSeasonMutex.RUnlock()
	return len(fake.endSeasonArgsForCall)
}

func (fake *FakeSeasonsRepository) EndSeasonCalls(stub func(context.Context, int64) (*seasons.Season, error)) {
	fake.endSeasonMutex.Lock()
	defer fake.endSeasonMutex.Unlock()
	fake.EndSeasonStub = stub
}

func (fake *FakeSeasonsRepository) EndSeasonArgsForCall(i int) (context.Context, int64) {
	fake.endSeasonMutex.RLock()
	defer fake.endSeasonMutex.RUnlock()
	argsForCall := fake.endSeasonArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSeasonsRepository) EndSeasonReturns(result1 *seasons.Season, result2 error) {
	fake.endSeasonMutex.Lock()
	defer fake.endSeasonMutex.Unlock()
	fake.EndSeasonStub = nil
	fake.endSeasonReturns = struct {
		result1 *seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) EndSeasonReturnsOnCall(i int, result1 *seasons.Season, result2 error) {
	fake.endSeasonMutex.Lock()
	defer fake.endSeasonMutex.Unlock()
	fake.EndSeasonStub = nil
	if fake.endSeasonReturnsOnCall == nil {
		fake.endSeasonReturnsOnCall = make(map[int]struct {
			result1 *seasons.Season
			result2 error
		})
	}
	fake.endSeasonReturnsOnCall[i] = struct {
		result1 *seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) GetActiveSeason(arg1 context.Context) (*seasons.Season, error) {
	fake.getActiveSeasonMutex.Lock()
	ret, specificReturn := fake.getActiveSeasonReturnsOnCall[len(fake.getActiveSeasonArgsForCall)]
	fake.getActiveSeasonArgsForCall = append(fake.getActiveSeasonArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetActiveSeasonStub
	fakeReturns := fake.getActiveSeasonReturns
	fake.recordInvocation("GetActiveSeason", []interface{}{arg1})
	fake.getActiveSeasonMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSeasonsRepository) GetActiveSeasonCallCount() int {
	fake.getActiveSeasonMutex.RLock()
	defer fake.getActiveSeasonMutex.RUnlock()
	return len(fake.getActiveSeasonArgsForCall)
}

func (fake *FakeSeasonsRepository) GetActiveSeasonCalls(stub func(context.Context) (*seasons.Season, error)) {
	fake.getActiveSeasonMutex.Lock()
	defer fake.getActiveSeasonMutex.Unlock()
	fake.GetActiveSeasonStub = stub
}

func (fake *FakeSeasonsRepository) GetActiveSeasonArgsForCall(i int) context.Context {
	fake.getActiveSeasonMutex.RLock()
	defer fake.getActiveSeasonMutex.RUnlock()
	argsForCall := fake.getActiveSeasonArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSeasonsRepository) GetActiveSeasonReturns(result1 *seasons.Season, result2 error) {
	fake.getActiveSeasonMutex.Lock()
	defer fake.getActiveSeasonMutex.Unlock()
	fake.GetActiveSeasonStub = nil
	fake.getActiveSeasonReturns = struct {
		result1 *seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) GetActiveSeasonReturnsOnCall(i int, result1 *seasons.Season, result2 error) {
	fake.getActiveSeasonMutex.Lock()
	defer fake.getActiveSeasonMutex.Unlock()
	fake.GetActiveSeasonStub = nil
	if fake.getActiveSeasonReturnsOnCall == nil {
		fake.getActiveSeasonReturnsOnCall = make(map[int]struct {
			result1 *seasons.Season
			result2 error
		})
	}
	fake.getActiveSeasonReturnsOnCall[i] = struct {
		result1 *seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) GetSeasons(arg1 context.Context) ([]*seasons.Season, error) {
	fake.getSeasonsMutex.Lock()
	ret, specificReturn := fake.getSeasonsReturnsOnCall[len(fake.getSeasonsArgsForCall)]
	fake.getSeasonsArgsForCall = append(fake.getSeasonsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetSeasonsStub
	fakeReturns := fake.getSeasonsReturns
	fake.recordInvocation("GetSeasons", []interface{}{arg1})
	fake.getSeasonsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSeasonsRepository) GetSeasonsCallCount() int {
	fake.getSeasonsMutex.RLock()
	defer fake.getSeasonsMutex.RUnlock()
	return len(fake.getSeasonsArgsForCall)
}

func (fake *FakeSeasonsRepository) GetSeasonsCalls(stub func(context.Context) ([]*seasons.Season, error)) {
	fake.getSeasonsMutex.Lock()
	defer fake.getSeasonsMutex.Unlock()
	fake.GetSeasonsStub = stub
}

func (fake *FakeSeasonsRepository) GetSeasonsArgsForCall(i int) context.Context {
	fake.getSeasonsMutex.RLock()
	defer fake.getSeasonsMutex.RUnlock()
	argsForCall := fake.getSeasonsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSeasonsRepository) GetSeasonsReturns(result1 []*seasons.Season, result2 error) {
	fake.getSeasonsMutex.Lock()
	defer fake.getSeasonsMutex.Unlock()
	fake.GetSeasonsStub = nil
	fake.getSeasonsReturns = struct {
		result1 []*seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) GetSeasonsReturnsOnCall(i int, result1 []*seasons.Season, result2 error) {
	fake.getSeasonsMutex.Lock()
	defer fake.getSeasonsMutex.Unlock()
	fake.GetSeasonsStub = nil
	if fake.getSeasonsReturnsOnCall == nil {
		fake.getSeasonsReturnsOnCall = make(map[int]struct {
			result1 []*seasons.Season
			result2 error
		})
	}
	fake.getSeasonsReturnsOnCall[i] = struct {
		result1 []*seasons.Season
		result2 error
	}{result1, result2}
}

func (fake *FakeSeasonsRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSeasonsRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ seasons.SeasonsRepository = new(FakeSeasonsRepository)
