// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"
	"time"

	"github.com/tobyrushton/padel-stats/libs/auth/sessions"
	"github.com/tobyrushton/padel-stats/libs/db/models"
)

type FakeSessionStore struct {
	CreateStub        func(context.Context, *models.Session) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.Session
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	FindByTokenIDStub        func(context.Context, string) (*models.Session, error)
	findByTokenIDMutex       sync.RWMutex
	findByTokenIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findByTokenIDReturns struct {
		result1 *models.Session
		result2 error
	}
	findByTokenIDReturnsOnCall map[int]struct {
		result1 *models.Session
		result2 error
	}
	RevokeByTokenIDStub        func(context.Context, string, time.Time) error
	revokeByTokenIDMutex       sync.RWMutex
	revokeByTokenIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
	}
	revokeByTokenIDReturns struct {
		result1 error
	}
	revokeByTokenIDReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSessionStore) Create(arg1 context.Context, arg2 *models.Session) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.Session
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSessionStore) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeSessionStore) CreateCalls(stub func(context.Context, *models.Session) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeSessionStore) CreateArgsForCall(i int) (context.Context, *models.Session) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionStore) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionStore) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionStore) FindByTokenID(arg1 context.Context, arg2 string) (*models.Session, error) {
	fake.findByTokenIDMutex.Lock()
	ret, specificReturn := fake.findByTokenIDReturnsOnCall[len(fake.findByTokenIDArgsForCall)]
	fake.findByTokenIDArgsForCall = append(fake.findByTokenIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindByTokenIDStub
	fakeReturns := fake.findByTokenIDReturns
	fake.recordInvocation("FindByTokenID", []interface{}{arg1, arg2})
	fake.findByTokenIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionStore) FindByTokenIDCallCount() int {
	fake.findByTokenIDMutex.RLock()
	defer fake.findByTokenIDMutex.RUnlock()
	return len(fake.findByTokenIDArgsForCall)
}

func (fake *FakeSessionStore) FindByTokenIDCalls(stub func(context.Context, string) (*models.Session, error)) {
	fake.findByTokenIDMutex.Lock()
	defer fake.findByTokenIDMutex.Unlock()
	fake.FindByTokenIDStub = stub
}

func (fake *FakeSessionStore) FindByTokenIDArgsForCall(i int) (context.Context, string) {
	fake.findByTokenIDMutex.RLock()
	defer fake.findByTokenIDMutex.RUnlock()
	argsForCall := fake.findByTokenIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionStore) FindByTokenIDReturns(result1 *models.Session, result2 error) {
	fake.findByTokenIDMutex.Lock()
	defer fake.findByTokenIDMutex.Unlock()
	fake.FindByTokenIDStub = nil
	fake.findByTokenIDReturns = struct {
		result1 *models.Session
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionStore) FindByTokenIDReturnsOnCall(i int, result1 *models.Session, result2 error) {
	fake.findByTokenIDMutex.Lock()
	defer fake.findByTokenIDMutex.Unlock()
	fake.FindByTokenIDStub = nil
	if fake.findByTokenIDReturnsOnCall == nil {
		fake.findByTokenIDReturnsOnCall = make(map[int]struct {
			result1 *models.Session
			result2 error
		})
	}
	fake.findByTokenIDReturnsOnCall[i] = struct {
		result1 *models.Session
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionStore) RevokeByTokenID(arg1 context.Context, arg2 string, arg3 time.Time) error {
	fake.revokeByTokenIDMutex.Lock()
	ret, specificReturn := fake.revokeByTokenIDReturnsOnCall[len(fake.revokeByTokenIDArgsForCall)]
	fake.revokeByTokenIDArgsForCall = append(fake.revokeByTokenIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
	}{arg1, arg2, arg3})
	stub := fake.RevokeByTokenIDStub
	fakeReturns := fake.revokeByTokenIDReturns
	fake.recordInvocation("RevokeByTokenID", []interface{}{arg1, arg2, arg3})
	fake.revokeByTokenIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSessionStore) RevokeByTokenIDCallCount() int {
	fake.revokeByTokenIDMutex.RLock()
	defer fake.revokeByTokenIDMutex.RUnlock()
	return len(fake.revokeByTokenIDArgsForCall)
}

func (fake *FakeSessionStore) RevokeByTokenIDCalls(stub func(context.Context, string, time.Time) error) {
	fake.revokeByTokenIDMutex.Lock()
	defer fake.revokeByTokenIDMutex.Unlock()
	fake.RevokeByTokenIDStub = stub
}

func (fake *FakeSessionStore) RevokeByTokenIDArgsForCall(i int) (context.Context, string, time.Time) {
	fake.revokeByTokenIDMutex.RLock()
	defer fake.revokeByTokenIDMutex.RUnlock()
	argsForCall := fake.revokeByTokenIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSessionStore) RevokeByTokenIDReturns(result1 error) {
	fake.revokeByTokenIDMutex.Lock()
	defer fake.revokeByTokenIDMutex.Unlock()
	fake.RevokeByTokenIDStub = nil
	fake.revokeByTokenIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionStore) RevokeByTokenIDReturnsOnCall(i int, result1 error) {
	fake.revokeByTokenIDMutex.Lock()
	defer fake.revokeByTokenIDMutex.Unlock()
	fake.RevokeByTokenIDStub = nil
	if fake.revokeByTokenIDReturnsOnCall == nil {
		fake.revokeByTokenIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.revokeByTokenIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSessionStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sessions.SessionStore = new(FakeSessionStore)
