// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/tobyrushton/padel-stats/libs/auth"
)

type FakeUserRepository struct {
	CreateUserStub        func(context.Context, *auth.UserRecord) error
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		arg1 context.Context
		arg2 *auth.UserRecord
	}
	createUserReturns struct {
		result1 error
	}
	createUserReturnsOnCall map[int]struct {
		result1 error
	}
	FindUserByUsernameStub        func(context.Context, string) (*auth.UserRecord, error)
	findUserByUsernameMutex       sync.RWMutex
	findUserByUsernameArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findUserByUsernameReturns struct {
		result1 *auth.UserRecord
		result2 error
	}
	findUserByUsernameReturnsOnCall map[int]struct {
		result1 *auth.UserRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUserRepository) CreateUser(arg1 context.Context, arg2 *auth.UserRecord) error {
	fake.createUserMutex.Lock()
	ret, specificReturn := fake.createUserReturnsOnCall[len(fake.createUserArgsForCall)]
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		arg1 context.Context
		arg2 *auth.UserRecord
	}{arg1, arg2})
	stub := fake.CreateUserStub
	fakeReturns := fake.createUserReturns
	fake.recordInvocation("CreateUser", []interface{}{arg1, arg2})
	fake.createUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeUserRepository) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *FakeUserRepository) CreateUserCalls(stub func(context.Context, *auth.UserRecord) error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = stub
}

func (fake *FakeUserRepository) CreateUserArgsForCall(i int) (context.Context, *auth.UserRecord) {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	argsForCall := fake.createUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) CreateUserReturns(result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserRepository) CreateUserReturnsOnCall(i int, result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	if fake.createUserReturnsOnCall == nil {
		fake.createUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserRepository) FindUserByUsername(arg1 context.Context, arg2 string) (*auth.UserRecord, error) {
	fake.findUserByUsernameMutex.Lock()
	ret, specificReturn := fake.findUserByUsernameReturnsOnCall[len(fake.findUserByUsernameArgsForCall)]
	fake.findUserByUsernameArgsForCall = append(fake.findUserByUsernameArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindUserByUsernameStub
	fakeReturns := fake.findUserByUsernameReturns
	fake.recordInvocation("FindUserByUsername", []interface{}{arg1, arg2})
	fake.findUserByUsernameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserRepository) FindUserByUsernameCallCount() int {
	fake.findUserByUsernameMutex.RLock()
	defer fake.findUserByUsernameMutex.RUnlock()
	return len(fake.findUserByUsernameArgsForCall)
}

func (fake *FakeUserRepository) FindUserByUsernameCalls(stub func(context.Context, string) (*auth.UserRecord, error)) {
	fake.findUserByUsernameMutex.Lock()
	defer fake.findUserByUsernameMutex.Unlock()
	fake.FindUserByUsernameStub = stub
}

func (fake *FakeUserRepository) FindUserByUsernameArgsForCall(i int) (context.Context, string) {
	fake.findUserByUsernameMutex.RLock()
	defer fake.findUserByUsernameMutex.RUnlock()
	argsForCall := fake.findUserByUsernameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) FindUserByUsernameReturns(result1 *auth.UserRecord, result2 error) {
	fake.findUserByUsernameMutex.Lock()
	defer fake.findUserByUsernameMutex.Unlock()
	fake.FindUserByUsernameStub = nil
	fake.findUserByUsernameReturns = struct {
		result1 *auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) FindUserByUsernameReturnsOnCall(i int, result1 *auth.UserRecord, result2 error) {
	fake.findUserByUsernameMutex.Lock()
	defer fake.findUserByUsernameMutex.Unlock()
	fake.FindUserByUsernameStub = nil
	if fake.findUserByUsernameReturnsOnCall == nil {
		fake.findUserByUsernameReturnsOnCall = make(map[int]struct {
			result1 *auth.UserRecord
			result2 error
		})
	}
	fake.findUserByUsernameReturnsOnCall[i] = struct {
		result1 *auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUserRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.UserRepository = new(FakeUserRepository)
