// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/tobyrushton/padel-stats/libs/auth"
)

type FakeUserRepository struct {
	ApproveUserByIDStub        func(context.Context, int64) error
	approveUserByIDMutex       sync.RWMutex
	approveUserByIDArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	approveUserByIDReturns struct {
		result1 error
	}
	approveUserByIDReturnsOnCall map[int]struct {
		result1 error
	}
	CreateUserStub        func(context.Context, *auth.UserRecord) error
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		arg1 context.Context
		arg2 *auth.UserRecord
	}
	createUserReturns struct {
		result1 error
	}
	createUserReturnsOnCall map[int]struct {
		result1 error
	}
	FindUserByIDStub        func(context.Context, int64) (*auth.UserRecord, error)
	findUserByIDMutex       sync.RWMutex
	findUserByIDArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	findUserByIDReturns struct {
		result1 *auth.UserRecord
		result2 error
	}
	findUserByIDReturnsOnCall map[int]struct {
		result1 *auth.UserRecord
		result2 error
	}
	FindUserByUsernameStub        func(context.Context, string) (*auth.UserRecord, error)
	findUserByUsernameMutex       sync.RWMutex
	findUserByUsernameArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findUserByUsernameReturns struct {
		result1 *auth.UserRecord
		result2 error
	}
	findUserByUsernameReturnsOnCall map[int]struct {
		result1 *auth.UserRecord
		result2 error
	}
	IsAdminStub        func(context.Context, int64) (bool, error)
	isAdminMutex       sync.RWMutex
	isAdminArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	isAdminReturns struct {
		result1 bool
		result2 error
	}
	isAdminReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	SearchUsersByQueryStub        func(context.Context, string) ([]*auth.UserRecord, error)
	searchUsersByQueryMutex       sync.RWMutex
	searchUsersByQueryArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	searchUsersByQueryReturns struct {
		result1 []*auth.UserRecord
		result2 error
	}
	searchUsersByQueryReturnsOnCall map[int]struct {
		result1 []*auth.UserRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUserRepository) ApproveUserByID(arg1 context.Context, arg2 int64) error {
	fake.approveUserByIDMutex.Lock()
	ret, specificReturn := fake.approveUserByIDReturnsOnCall[len(fake.approveUserByIDArgsForCall)]
	fake.approveUserByIDArgsForCall = append(fake.approveUserByIDArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.ApproveUserByIDStub
	fakeReturns := fake.approveUserByIDReturns
	fake.recordInvocation("ApproveUserByID", []interface{}{arg1, arg2})
	fake.approveUserByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeUserRepository) ApproveUserByIDCallCount() int {
	fake.approveUserByIDMutex.RLock()
	defer fake.approveUserByIDMutex.RUnlock()
	return len(fake.approveUserByIDArgsForCall)
}

func (fake *FakeUserRepository) ApproveUserByIDCalls(stub func(context.Context, int64) error) {
	fake.approveUserByIDMutex.Lock()
	defer fake.approveUserByIDMutex.Unlock()
	fake.ApproveUserByIDStub = stub
}

func (fake *FakeUserRepository) ApproveUserByIDArgsForCall(i int) (context.Context, int64) {
	fake.approveUserByIDMutex.RLock()
	defer fake.approveUserByIDMutex.RUnlock()
	argsForCall := fake.approveUserByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) ApproveUserByIDReturns(result1 error) {
	fake.approveUserByIDMutex.Lock()
	defer fake.approveUserByIDMutex.Unlock()
	fake.ApproveUserByIDStub = nil
	fake.approveUserByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserRepository) ApproveUserByIDReturnsOnCall(i int, result1 error) {
	fake.approveUserByIDMutex.Lock()
	defer fake.approveUserByIDMutex.Unlock()
	fake.ApproveUserByIDStub = nil
	if fake.approveUserByIDReturnsOnCall == nil {
		fake.approveUserByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.approveUserByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserRepository) CreateUser(arg1 context.Context, arg2 *auth.UserRecord) error {
	fake.createUserMutex.Lock()
	ret, specificReturn := fake.createUserReturnsOnCall[len(fake.createUserArgsForCall)]
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		arg1 context.Context
		arg2 *auth.UserRecord
	}{arg1, arg2})
	stub := fake.CreateUserStub
	fakeReturns := fake.createUserReturns
	fake.recordInvocation("CreateUser", []interface{}{arg1, arg2})
	fake.createUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeUserRepository) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *FakeUserRepository) CreateUserCalls(stub func(context.Context, *auth.UserRecord) error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = stub
}

func (fake *FakeUserRepository) CreateUserArgsForCall(i int) (context.Context, *auth.UserRecord) {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	argsForCall := fake.createUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) CreateUserReturns(result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserRepository) CreateUserReturnsOnCall(i int, result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	if fake.createUserReturnsOnCall == nil {
		fake.createUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserRepository) FindUserByID(arg1 context.Context, arg2 int64) (*auth.UserRecord, error) {
	fake.findUserByIDMutex.Lock()
	ret, specificReturn := fake.findUserByIDReturnsOnCall[len(fake.findUserByIDArgsForCall)]
	fake.findUserByIDArgsForCall = append(fake.findUserByIDArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.FindUserByIDStub
	fakeReturns := fake.findUserByIDReturns
	fake.recordInvocation("FindUserByID", []interface{}{arg1, arg2})
	fake.findUserByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserRepository) FindUserByIDCallCount() int {
	fake.findUserByIDMutex.RLock()
	defer fake.findUserByIDMutex.RUnlock()
	return len(fake.findUserByIDArgsForCall)
}

func (fake *FakeUserRepository) FindUserByIDCalls(stub func(context.Context, int64) (*auth.UserRecord, error)) {
	fake.findUserByIDMutex.Lock()
	defer fake.findUserByIDMutex.Unlock()
	fake.FindUserByIDStub = stub
}

func (fake *FakeUserRepository) FindUserByIDArgsForCall(i int) (context.Context, int64) {
	fake.findUserByIDMutex.RLock()
	defer fake.findUserByIDMutex.RUnlock()
	argsForCall := fake.findUserByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) FindUserByIDReturns(result1 *auth.UserRecord, result2 error) {
	fake.findUserByIDMutex.Lock()
	defer fake.findUserByIDMutex.Unlock()
	fake.FindUserByIDStub = nil
	fake.findUserByIDReturns = struct {
		result1 *auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) FindUserByIDReturnsOnCall(i int, result1 *auth.UserRecord, result2 error) {
	fake.findUserByIDMutex.Lock()
	defer fake.findUserByIDMutex.Unlock()
	fake.FindUserByIDStub = nil
	if fake.findUserByIDReturnsOnCall == nil {
		fake.findUserByIDReturnsOnCall = make(map[int]struct {
			result1 *auth.UserRecord
			result2 error
		})
	}
	fake.findUserByIDReturnsOnCall[i] = struct {
		result1 *auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) FindUserByUsername(arg1 context.Context, arg2 string) (*auth.UserRecord, error) {
	fake.findUserByUsernameMutex.Lock()
	ret, specificReturn := fake.findUserByUsernameReturnsOnCall[len(fake.findUserByUsernameArgsForCall)]
	fake.findUserByUsernameArgsForCall = append(fake.findUserByUsernameArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindUserByUsernameStub
	fakeReturns := fake.findUserByUsernameReturns
	fake.recordInvocation("FindUserByUsername", []interface{}{arg1, arg2})
	fake.findUserByUsernameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserRepository) FindUserByUsernameCallCount() int {
	fake.findUserByUsernameMutex.RLock()
	defer fake.findUserByUsernameMutex.RUnlock()
	return len(fake.findUserByUsernameArgsForCall)
}

func (fake *FakeUserRepository) FindUserByUsernameCalls(stub func(context.Context, string) (*auth.UserRecord, error)) {
	fake.findUserByUsernameMutex.Lock()
	defer fake.findUserByUsernameMutex.Unlock()
	fake.FindUserByUsernameStub = stub
}

func (fake *FakeUserRepository) FindUserByUsernameArgsForCall(i int) (context.Context, string) {
	fake.findUserByUsernameMutex.RLock()
	defer fake.findUserByUsernameMutex.RUnlock()
	argsForCall := fake.findUserByUsernameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) FindUserByUsernameReturns(result1 *auth.UserRecord, result2 error) {
	fake.findUserByUsernameMutex.Lock()
	defer fake.findUserByUsernameMutex.Unlock()
	fake.FindUserByUsernameStub = nil
	fake.findUserByUsernameReturns = struct {
		result1 *auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) FindUserByUsernameReturnsOnCall(i int, result1 *auth.UserRecord, result2 error) {
	fake.findUserByUsernameMutex.Lock()
	defer fake.findUserByUsernameMutex.Unlock()
	fake.FindUserByUsernameStub = nil
	if fake.findUserByUsernameReturnsOnCall == nil {
		fake.findUserByUsernameReturnsOnCall = make(map[int]struct {
			result1 *auth.UserRecord
			result2 error
		})
	}
	fake.findUserByUsernameReturnsOnCall[i] = struct {
		result1 *auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) IsAdmin(arg1 context.Context, arg2 int64) (bool, error) {
	fake.isAdminMutex.Lock()
	ret, specificReturn := fake.isAdminReturnsOnCall[len(fake.isAdminArgsForCall)]
	fake.isAdminArgsForCall = append(fake.isAdminArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.IsAdminStub
	fakeReturns := fake.isAdminReturns
	fake.recordInvocation("IsAdmin", []interface{}{arg1, arg2})
	fake.isAdminMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserRepository) IsAdminCallCount() int {
	fake.isAdminMutex.RLock()
	defer fake.isAdminMutex.RUnlock()
	return len(fake.isAdminArgsForCall)
}

func (fake *FakeUserRepository) IsAdminCalls(stub func(context.Context, int64) (bool, error)) {
	fake.isAdminMutex.Lock()
	defer fake.isAdminMutex.Unlock()
	fake.IsAdminStub = stub
}

func (fake *FakeUserRepository) IsAdminArgsForCall(i int) (context.Context, int64) {
	fake.isAdminMutex.RLock()
	defer fake.isAdminMutex.RUnlock()
	argsForCall := fake.isAdminArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) IsAdminReturns(result1 bool, result2 error) {
	fake.isAdminMutex.Lock()
	defer fake.isAdminMutex.Unlock()
	fake.IsAdminStub = nil
	fake.isAdminReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) IsAdminReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isAdminMutex.Lock()
	defer fake.isAdminMutex.Unlock()
	fake.IsAdminStub = nil
	if fake.isAdminReturnsOnCall == nil {
		fake.isAdminReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isAdminReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) SearchUsersByQuery(arg1 context.Context, arg2 string) ([]*auth.UserRecord, error) {
	fake.searchUsersByQueryMutex.Lock()
	ret, specificReturn := fake.searchUsersByQueryReturnsOnCall[len(fake.searchUsersByQueryArgsForCall)]
	fake.searchUsersByQueryArgsForCall = append(fake.searchUsersByQueryArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.SearchUsersByQueryStub
	fakeReturns := fake.searchUsersByQueryReturns
	fake.recordInvocation("SearchUsersByQuery", []interface{}{arg1, arg2})
	fake.searchUsersByQueryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserRepository) SearchUsersByQueryCallCount() int {
	fake.searchUsersByQueryMutex.RLock()
	defer fake.searchUsersByQueryMutex.RUnlock()
	return len(fake.searchUsersByQueryArgsForCall)
}

func (fake *FakeUserRepository) SearchUsersByQueryCalls(stub func(context.Context, string) ([]*auth.UserRecord, error)) {
	fake.searchUsersByQueryMutex.Lock()
	defer fake.searchUsersByQueryMutex.Unlock()
	fake.SearchUsersByQueryStub = stub
}

func (fake *FakeUserRepository) SearchUsersByQueryArgsForCall(i int) (context.Context, string) {
	fake.searchUsersByQueryMutex.RLock()
	defer fake.searchUsersByQueryMutex.RUnlock()
	argsForCall := fake.searchUsersByQueryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserRepository) SearchUsersByQueryReturns(result1 []*auth.UserRecord, result2 error) {
	fake.searchUsersByQueryMutex.Lock()
	defer fake.searchUsersByQueryMutex.Unlock()
	fake.SearchUsersByQueryStub = nil
	fake.searchUsersByQueryReturns = struct {
		result1 []*auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) SearchUsersByQueryReturnsOnCall(i int, result1 []*auth.UserRecord, result2 error) {
	fake.searchUsersByQueryMutex.Lock()
	defer fake.searchUsersByQueryMutex.Unlock()
	fake.SearchUsersByQueryStub = nil
	if fake.searchUsersByQueryReturnsOnCall == nil {
		fake.searchUsersByQueryReturnsOnCall = make(map[int]struct {
			result1 []*auth.UserRecord
			result2 error
		})
	}
	fake.searchUsersByQueryReturnsOnCall[i] = struct {
		result1 []*auth.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUserRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.UserRepository = new(FakeUserRepository)
