name: Deploy

on:
  push:
    branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v6
            
            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version-file: go.mod
            
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                node-version-file: package.json
            
            - name: Install dependencies
              run: npm install

            - name: Install Frontend Dependencies
              run: cd pkg/www && npm install

            - name: Deploy to production
              run: npx sst deploy --stage production
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                NEON_ORG_ID: ${{ secrets.NEON_ORG_ID }}
                NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                CLOUDFLARE_DEFAULT_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_DEFAULT_ACCOUNT_ID }}
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
                JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
            
            - name: Init DB migrations
              run: npx sst shell --stage production go run ./cmd/migrate init
              env:
                NEON_ORG_ID: ${{ secrets.NEON_ORG_ID }}
                NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

            - name: Apply DB migrations
              run: npx sst shell --stage production go run ./cmd/migrate migrate
              env:
                NEON_ORG_ID: ${{ secrets.NEON_ORG_ID }}
                NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
